baseurl = "https://csudsi.netlify.com/"
title = "CSUC DSI"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Robin Donatello"
disqusShortname = "XXX"
googleAnalytics = "XXX"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


#[Author]
#    name = " default name"
#    profile = "www.datascience.csuchico.edu"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Chico State Data Science"
    description = "Without data, you're just another person with an opinion. - W.E. Deming"
    github = "https://github.com/csucdsi"
    gitlab = ""
    linkedin = ""
    gplus = ""
    twitter = ""
    stackoverflow = ""
    email = "datascience@csuchico.edu"
    opengraph = false
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    math = true

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Current News"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About the DSI"
    url = "/page/about/"
    weight = 2
    

[[menu.main]]
    name = "Related Curriculum"
    url = "/page/courses/"
    weight = 3

[[menu.main]]
    name = "Event Calendar"
    url = "/page/events/"
    weight = 4
    
[[menu.main]]
    name = "Contact Us"
    url = "/page/contact/"
    weight = 5

