baseurl = "https://csudsi.netlify.com/"
title = "CSUC DSI"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Robin Donatello"
disqusShortname = "XXX"
googleAnalytics = "XXX"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Author]
    name = ""
    profile = "www.datascience.csuchico.edu"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Chico State Data Science"
    description = "Without data, you're just another person with an opinion. - W.E. Deming"
    github = "https://github.com/csucdsi"
    gitlab = ""
    linkedin = ""
    gplus = ""
    twitter = ""
    stackoverflow = ""
    email = "datascience@csuchico.onmicrosoft.com"
    opengraph = false
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2
    
[[menu.main]]
    name = "Workshops"
    url = "/workshop/"
    weight = 3

[[menu.main]]
    name = "Curriculum"
    url = "/page/courses/"
    weight = 4
    
[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 5

