---
title: Sp17 R Workshop Series - Fitting intro statistical models
author: ''
date: '2017-04-28'
slug: stat_models_brief
categories:
  - R
  - statistics
tags:
  - R
  - statistics
  - analysis
---

# Logistics / Setup

* **Date:** Friday April 28, 2017 
* **Time:** 3-4:30 pm
* **Location:** MLIB 442
* **Presenter:** Robin Donatello: rdonatello@csuchico.edu 

## Learning Objectives

In this workshop you will learn and practice the following: 

* How to conduct a handful of statistical analysis techniques using R

**Note: This workshop does not cover the Statistical Methodology or theory behind these statistical procedures. This workshop assumes that you have checked model assumptions and have chosen the most appropriate model for the research question being analyzed. **

## Pre-Requirements / Setup 
* A laptop with R (v3.3.0+), and RStudio (v1.1.136) installed and operational. 
* The [cdc]() data downloaded and put into a DSI workshop folder. 
* `ggplot2` version 2.2.1 or higher installed. 
* `gridExtra` version 2.2.1 or higher installed

Need a refresher on how to make plots? See the [Data ViZ](https://csudsi.netlify.com/workshop/ggplot2_intro1/) DSI tutorial from April 21, 2017. 


[Workshop Details & Materials](/workshop/stat_models_brief/)
