<!DOCTYPE html>
<html lang="en-us">

  <head>
  <meta charset="utf-8">
  <meta name="robots" content="all,follow">
  <meta name="googlebot" content="index,follow,snippet,archive">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <title>Statistical analysis functions using R</title>
  <meta name="author" content="Robin Donatello" />
  
  
  
  
  <meta name="keywords" content="DataScience">
  
  
  <meta name="description" content="2017-04-28 DSI Workshop">

  <meta name="generator" content="Hugo 0.75.1" />

  
  <link href='//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,500,700,800' rel='stylesheet' type='text/css'>

  
  <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.11.2/css/all.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  
  <link href="/css/animate.css" rel="stylesheet">

  
  
    <link href="/css/style.marsala.css" rel="stylesheet" id="theme-stylesheet">
  

  
  <link href="/css/custom.css" rel="stylesheet">

  
  
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  

  
  <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon" />
  <link rel="apple-touch-icon" href="/img/apple-touch-icon.png" />

  
  <link href="/css/owl.carousel.css" rel="stylesheet">
  <link href="/css/owl.theme.css" rel="stylesheet">

  
  <link rel="alternate" href="/index.xml" type="application/rss+xml" title="Chico State DSI Blog">

  
  
  
  
  
  
  
  

  
  <meta name="twitter:card" content="summary">
  
  <meta name="twitter:title" content="Statistical analysis functions using R">
  
  <meta name="twitter:description" content="2017-04-28 DSI Workshop">
  

 
  <script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX&#45;AMS&#45;MML_HTMLorMML" type="text/javascript"></script>
  <script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}}); </script>
  
</head>


  <body>

    <div id="all">

        <header class="navbar-affixed-top" data-spy="affix" data-offset-top="62">
    <div class="navbar navbar-default yamm" role="navigation" id="navbar">    
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand home" href="/">
                    <img src="/img/logo.png" alt="Statistical analysis functions using R logo" class="hidden-xs hidden-sm">
                    <img src="/img/logo.png" alt="Statistical analysis functions using R logo" class="visible-xs visible-sm">
                    <span class="sr-only">Statistical analysis functions using R - go to homepage</span>
                </a>
                <div class="navbar-buttons">
                    <button type="button" class="navbar-toggle btn-template-main" data-toggle="collapse" data-target="#navigation">
                      <span class="sr-only">Toggle Navigation</span>
                        <i class="fas fa-align-justify"></i>
                    </button>
                </div>
            </div>
            

            <div class="navbar-collapse collapse" id="navigation">
                <ul class="nav navbar-nav navbar-right">
                  
                  
                  
                  <li class="dropdown">
                    
                    <a href="/blog/">Blog</a>
                    
                  </li>
                  
                  
                  <li class="dropdown">
                    
                    <a href="https://www.csuchico.edu/datascience/">DSI Homepage</a>
                    
                  </li>
                  
                </ul>
            </div>
            

            <div class="collapse clearfix" id="search">    
                <form class="navbar-form" role="search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search">
                        <span class="input-group-btn">
                    <button type="submit" class="btn btn-template-main"><i class="fas fa-search"></i></button>
                </span>
                    </div>
                </form>
            </div>
            
        </div>
    </div>
</header>




        <div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Statistical analysis functions using R</h1>
            </div>
        </div>
    </div>
</div>


        <div id="content">
            <div class="container">

                <div class="row">

                    

                    <div class="col-md-9" id="blog-post">

                        
                          <p class="text-muted text-uppercase mb-small text-right">
                            By <a href="#">Robin Donatello</a>
                            
                            
                          </p>
                        

                        <div id="post-content">
                          


<div id="learning-objectives" class="section level2">
<h2>Learning Objectives</h2>
<p>In this workshop you will learn and practice the following:</p>
<ul>
<li>How to conduct a handful of statistical analysis techniques using R</li>
</ul>
<p><strong>Note: This workshop does not cover the Statistical Methodology or theory behind these statistical procedures. This workshop assumes that you have checked model assumptions and have chosen the most appropriate model for the research question being analyzed. </strong></p>
</div>
<div id="pre-requirements-setup" class="section level2">
<h2>Pre-Requirements / Setup</h2>
<ul>
<li>A laptop with R (v3.3.0+), and RStudio (v1.1.136) installed and operational.</li>
<li>The (/event/stat_models_brief/cdc.txt) data downloaded and put into a DSI workshop folder.</li>
<li><code>ggplot2</code> version 2.2.1 or higher installed.</li>
<li><code>gridExtra</code> version 2.2.1 or higher installed</li>
</ul>
<p>Need a refresher on how to make plots? See the <a href="datascience.csuchico.edu#ggplot">Data ViZ</a> DSI tutorial from April 21, 2017.</p>
</div>
<div id="sticky-notes" class="section level2">
<h2>Sticky notes</h2>
<p>We will use two colors of sticky notes to provide immediate feedback. I picked up this trick at a <a href="https://software-carpentry.org">Software Carpentry</a> lesson.</p>
<ul>
<li><p>While you are following along just fine, have the <span style="color:blue;">blue </span> sticky note on your laptop.</p></li>
<li><p>When you run into trouble or have a question, switch to the <span style="color:red;">red </span> sticky note. This will notify me or a TA that you have a question or need help.</p></li>
</ul>
<p>At the end of the session you will use these notes to provide feedback.</p>
<ul>
<li>Something that you enjoyed or worked well, write on the <span style="color:blue;">blue </span> note.<br />
</li>
<li>Something that could be improved, write on the <span style="color:red;">red </span> note.</li>
</ul>
</div>
<div id="data" class="section level1">
<h1>Data</h1>
<p>The data comes from the Center for Disease Control (CDC), which has been conducting the Behavioral Risk Ractor Surveillance System (BRFSS) since 1984.</p>
<p>BRFSS is the nation’s premier system of health-related telephone surveys that collect state data about U.S. residents regarding their health-related risk behaviors, chronic health conditions, and use of preventive services.</p>
<p>More information on the survey and data can be found at <a href="https://www.cdc.gov/brfss/" class="uri">https://www.cdc.gov/brfss/</a></p>
<div id="read-in-the-data" class="section level2">
<h2>Read in the data</h2>
<p>The data we are using comes from a random sample of 20,000 participants from this survey.</p>
<pre class="r"><code>cdc &lt;- read.table(&quot;stat_models_brief/cdc.txt&quot;, header=TRUE, sep=&quot;\t&quot;)</code></pre>
</div>
<div id="data-management-cleaning" class="section level2">
<h2>Data Management / cleaning</h2>
<p>Let’s create some variables that we’ll analyze throughout this tutorial.</p>
<p>The BEFSS asks participants how much they weigh, and how much they want to weigh. Let’s create a difference between the two to measure whether the participants feel the are under, or overweight.
<strong>Create the variable <code>wtdiff</code> as <code>wtdesire</code> - <code>weight</code>, so a positive value means they want to gain weight.</strong></p>
<pre class="r"><code>cdc$wtdiff &lt;- cdc$wtdesire - cdc$weight</code></pre>
</div>
</div>
<div id="simple-analysis" class="section level1">
<h1>Simple Analysis</h1>
<pre class="r"><code>library(ggplot2)
library(gridExtra)

# Optional settings for cleaning up the resulting knitted document 
library(knitr)
opts_chunk$set(warning=FALSE, message=FALSE,  
               fig.align = &#39;center&#39;,  fig.width=6, fig.height=4)</code></pre>
<div id="one-sample-t-test-for-a-mean" class="section level3">
<h3>One sample T-test for a mean</h3>
<p><strong>Are people on average happy with their weight?</strong></p>
<ol style="list-style-type: decimal">
<li>Look at your data. Calculate summary statistics and a plot.</li>
</ol>
<pre class="r"><code>summary(cdc$wtdiff)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## -300.00  -21.00  -10.00  -14.59    0.00  500.00</code></pre>
<pre class="r"><code>a &lt;- ggplot(cdc, aes(x=wtdiff)) + geom_histogram() + theme_bw()
b &lt;- ggplot(cdc, aes(x=1, y=wtdiff)) + geom_boxplot() + theme_bw()
grid.arrange(a, b, nrow=1)</code></pre>
<p><img src="/event/2017-04-28_stat_models_brief_files/figure-html/unnamed-chunk-4-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>There are some people who report wanting to gain 300 and 500 lbs. Let’s consider them outliers and remove them from our analyses by overwriting the <code>cdc</code> data set with a subset of rows, where <code>wtdiff</code> is less than 200.</p>
<pre class="r"><code>cdc &lt;- subset(cdc, wtdiff &lt; 200)</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Use a 1-sample T(Z)-test for no difference (<code>wtdiff</code> = 0)</li>
</ol>
<pre class="r"><code>t.test(cdc$wtdiff, mu=0, alternative=&quot;two.sided&quot;, conf.level = .95)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  cdc$wtdiff
## t = -87.455, df = 19997, p-value &lt; 2.2e-16
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -14.95903 -14.30320
## sample estimates:
## mean of x 
## -14.63111</code></pre>
<p>On average people want to weigh 14.6 (95% CI 14.3 to 15) lbs less than they do now.</p>
</div>
<div id="one-sample-test-for-a-proportion" class="section level3">
<h3>One sample test for a proportion</h3>
<p><strong>What is the proportion of survey participants who have smoked in the past 100 days?</strong></p>
<ol style="list-style-type: decimal">
<li>Look at your data. Calculate frequency and percent tables.</li>
</ol>
<pre class="r"><code>table(cdc$smoke100)</code></pre>
<pre><code>## 
##     0     1 
## 10558  9440</code></pre>
<pre class="r"><code>prop.table(table(cdc$smoke100))</code></pre>
<pre><code>## 
##         0         1 
## 0.5279528 0.4720472</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Conduct a 1-sample test of proportions to see if less than half of the participants smoke.</li>
</ol>
<pre class="r"><code>prop.test(x=9440, n=19998, p=.5)</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  9440 out of 19998, null probability 0.5
## X-squared = 62.391, df = 1, p-value = 2.817e-15
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.4651092 0.4789960
## sample estimates:
##         p 
## 0.4720472</code></pre>
<p>Significantly less than half 9440 (47%) of survey participants reported smoking in the past 100 days.</p>
<p><em>Since <code>smoke100</code> is treated by R to be a numeric variable, we can utilize the theoretical property that a proportion is a mean of a binary variable and use a <code>t.test()</code>.</em></p>
<pre class="r"><code>t.test(cdc$smoke100, mu=.5)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  cdc$smoke100
## t = -7.918, df = 19997, p-value = 2.538e-15
## alternative hypothesis: true mean is not equal to 0.5
## 95 percent confidence interval:
##  0.4651276 0.4789668
## sample estimates:
## mean of x 
## 0.4720472</code></pre>
</div>
<div id="two-sample-t-test-for-a-difference-in-means" class="section level3">
<h3>Two sample t-test for a difference in means</h3>
<p><strong>Do males and females have different perceptions on their weight</strong></p>
<ol style="list-style-type: decimal">
<li>Look at the data by creating a boxplot and density plot of <code>wtdiff</code> for each level of <code>gender</code>.</li>
</ol>
<pre class="r"><code>ggplot(cdc, aes(x=wtdiff, col=gender)) + geom_density() + theme_bw()</code></pre>
<p><img src="/event/2017-04-28_stat_models_brief_files/figure-html/unnamed-chunk-10-1.png" width="576" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot(cdc, aes(y=wtdiff, x=gender, fill=gender)) + geom_boxplot() + theme_bw()</code></pre>
<p><img src="/event/2017-04-28_stat_models_brief_files/figure-html/unnamed-chunk-10-2.png" width="576" style="display: block; margin: auto;" />
Looks like pretty similar distributions.</p>
<ol start="2" style="list-style-type: decimal">
<li>Use <code>t.test()</code> function with <strong>model notation: y ~ x</strong>.</li>
</ol>
<pre class="r"><code>t.test(wtdiff~gender, data=cdc)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  wtdiff by gender
## t = -22.294, df = 19979, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -8.004944 -6.711138
## sample estimates:
## mean in group f mean in group m 
##       -18.15118       -10.79314</code></pre>
<p>On average, males want to loose 10.8 lbs whereas females want to loose 18.2 lbs. We are 95% confident that females on average want to loose 6.7 to 8.0 more lbs compared to males.</p>
</div>
<div id="two-sample-z-test-for-a-difference-in-proportions" class="section level3">
<h3>Two sample Z-test for a difference in proportions</h3>
<p><strong>Does a higher proportion of males smoke than females?</strong></p>
<ol style="list-style-type: decimal">
<li>Look at the data.</li>
</ol>
<pre class="r"><code>addmargins(table(cdc$smoke100, cdc$gender))</code></pre>
<pre><code>##      
##           f     m   Sum
##   0    6012  4546 10558
##   1    4419  5021  9440
##   Sum 10431  9567 19998</code></pre>
<pre class="r"><code>prop.table(table(cdc$smoke100, cdc$gender), margin=2)</code></pre>
<pre><code>##    
##             f         m
##   0 0.5763589 0.4751751
##   1 0.4236411 0.5248249</code></pre>
<p>42% of females smoke compared to 52% of males.</p>
<ol start="2" style="list-style-type: decimal">
<li>Since <code>smoke100</code> is 0/1 numeric, we can still use <code>t.test()</code> with model notation.</li>
</ol>
<pre class="r"><code>t.test(smoke100 ~ gender, data=cdc)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  smoke100 by gender
## t = -14.385, df = 19809, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.11497149 -0.08739621
## sample estimates:
## mean in group f mean in group m 
##       0.4236411       0.5248249</code></pre>
<p>We could also use <code>prop.test()</code> with the frequency table numbers above.</p>
<pre class="r"><code>prop.test(x=c(4419, 5021), n=c(10431, 9567))</code></pre>
<pre><code>## 
##  2-sample test for equality of proportions with continuity correction
## 
## data:  c(4419, 5021) out of c(10431, 9567)
## X-squared = 204.6, df = 1, p-value &lt; 2.2e-16
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  -0.11507015 -0.08729755
## sample estimates:
##    prop 1    prop 2 
## 0.4236411 0.5248249</code></pre>
</div>
<div id="anova" class="section level3">
<h3>ANOVA</h3>
<p><strong>Does the desired weight differ across different general health reporting categories?</strong></p>
<ol style="list-style-type: decimal">
<li>Look at the data. Side by side boxplots with overlay violin plots are great here.</li>
</ol>
<pre class="r"><code>ggplot(cdc, aes(y=wtdesire, x=genhlth, fill=genhlth)) + geom_boxplot() + 
        theme_bw() + 
        stat_summary(fun = &quot;mean&quot;, pch=17, geom=&quot;point&quot;,  size = 2) + # adds the mean as a diamond
        scale_fill_discrete(guide=FALSE) # get rid of the legend created by the fill= argument</code></pre>
<p><img src="/event/2017-04-28_stat_models_brief_files/figure-html/unnamed-chunk-15-1.png" width="576" style="display: block; margin: auto;" /></p>
<ol start="2" style="list-style-type: decimal">
<li>Conduct an ANOVA</li>
</ol>
<pre class="r"><code>model &lt;- aov(wtdesire~genhlth, data=cdc) #aov() is the workhorse function
summary(model) # prints it in an easy to ready fashion. </code></pre>
<pre><code>##                Df   Sum Sq Mean Sq F value   Pr(&gt;F)    
## genhlth         4    21206    5302     5.3 0.000291 ***
## Residuals   19993 20000399    1000                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>At least one group has a different average desired weight (p&lt;.0003).</p>
<ol start="3" style="list-style-type: decimal">
<li>Follow-up with finding out which pairs of groups are different.</li>
</ol>
<pre class="r"><code>TukeyHSD(model)</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = wtdesire ~ genhlth, data = cdc)
## 
## $genhlth
##                            diff        lwr       upr     p adj
## fair-excellent       1.78916580 -0.5099737 4.0883053 0.2102493
## good-excellent       2.63645738  0.9303678 4.3425470 0.0002422
## poor-excellent       0.08699155 -3.4620206 3.6360037 0.9999955
## very good-excellent  2.08422232  0.4512445 3.7172001 0.0045430
## good-fair            0.84729158 -1.3886656 3.0832487 0.8397624
## poor-fair           -1.70217425 -5.5341776 2.1298291 0.7445592
## very good-fair       0.29505652 -1.8856267 2.4757397 0.9960519
## poor-good           -2.54946583 -6.0578770 0.9589454 0.2745906
## very good-good      -0.55223506 -2.0949854 0.9905153 0.8659094
## very good-poor       1.99723077 -1.4762148 5.4706763 0.5176727</code></pre>
<p>The only two groups whose averages differ significantly from each other are:</p>
<ul>
<li>those reporting to be in good health want to loose on average 2.63 (0.93, 4.34) lbs more than those who report being in excellent health (p=.0002).</li>
<li>those reporting to be in very good health want to loose 2.1 (0.5, 3.7) lbs more than those who report being in excellent health (p=.0045)</li>
</ul>
</div>
<div id="chi-squared-test-of" class="section level3">
<h3>Chi-Squared test of</h3>
<ul>
<li>Association</li>
<li>Independence</li>
<li>Goodness of fit</li>
<li>Equal proportions</li>
</ul>
</div>
<div id="linear-regression-and-correlation" class="section level3">
<h3>Linear Regression and Correlation</h3>
<p><strong>Is there a linear relationship between how much a person weighs and their desired weight?</strong></p>
<ol style="list-style-type: decimal">
<li>Guess what. Yea. Look at your data.</li>
</ol>
<pre class="r"><code>ggplot(cdc, aes(x=weight, y=wtdesire)) + 
      geom_point(size=.5) + # lots of points so i&#39;m shrinking the size of the point
      geom_smooth(se=FALSE, col=&quot;red&quot;) + # adds a smoothing trend line
      geom_smooth(se=FALSE, method=&quot;lm&quot;, col=&quot;blue&quot;) + # adds a best fit line
      theme_bw()</code></pre>
<p><img src="/event/2017-04-28_stat_models_brief_files/figure-html/unnamed-chunk-18-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>A linear model may not be appropriate for those who weigh over 250-300 lbs.</p>
<ol start="2" style="list-style-type: decimal">
<li>Fit a linear regression line for those who weigh less than 250 lbs.
The workhorse function here is <code>lm()</code>, but like <code>aov()</code> looks better after being wrapped in a <code>summary()</code>.</li>
</ol>
<pre class="r"><code>lt250 &lt;- subset(cdc, weight&lt;=250)

linear.model &lt;- lm(wtdesire ~ weight, data=lt250)
summary(linear.model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = wtdesire ~ weight, data = lt250)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -114.963   -8.398    0.804   10.587  112.254 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 35.42780    0.60440   58.62   &lt;2e-16 ***
## weight       0.71014    0.00357  198.89   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 16.95 on 19347 degrees of freedom
## Multiple R-squared:  0.6716, Adjusted R-squared:  0.6715 
## F-statistic: 3.956e+04 on 1 and 19347 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The linear regression equation is <span class="math display">\[y = 35.4 + .71x\]</span>.</p>
<p>The amount of weight someone wants to loose significantly increases by 0.71 lbs for ever additional pound they weigh.</p>
<p>Calculate the simple correlation between actual and desired weight.</p>
<pre class="r"><code>cor(lt250$wtdesire, lt250$weight)</code></pre>
<pre><code>## [1] 0.8194856</code></pre>
</div>
<div id="multple-linear-regression" class="section level3">
<h3>Multple Linear Regression</h3>
<p>You can add multiple predictors to any regression model by adding the variable names using a <code>+</code>.</p>
<p><strong>How does gender affect the relationship between how much a person weighs and their desired weight?</strong></p>
<ol style="list-style-type: decimal">
<li>Guess what. Yea. Look at your data.</li>
</ol>
<pre class="r"><code>ggplot(cdc, aes(x=weight, y=wtdesire, col=gender)) + 
      geom_point(size=.5) + 
      geom_smooth(se=FALSE) + # adds a smoothing trend line - per group
      theme_bw()</code></pre>
<p><img src="/event/2017-04-28_stat_models_brief_files/figure-html/unnamed-chunk-21-1.png" width="576" style="display: block; margin: auto;" /></p>
<ol start="2" style="list-style-type: decimal">
<li>Fit the additive linear model of weight + gender</li>
</ol>
<pre class="r"><code>summary(lm(wtdesire ~ weight + gender, data=lt250))</code></pre>
<pre><code>## 
## Call:
## lm(formula = wtdesire ~ weight + gender, data = lt250)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -98.320  -6.899   0.154   6.634 119.743 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 53.912757   0.490459   109.9   &lt;2e-16 ***
## weight       0.527835   0.003158   167.1   &lt;2e-16 ***
## genderm     25.087468   0.215985   116.2   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 13.01 on 19346 degrees of freedom
## Multiple R-squared:  0.8065, Adjusted R-squared:  0.8065 
## F-statistic: 4.032e+04 on 2 and 19346 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Note the coefficient for gender: <code>genderm</code>. R appends the factor level that it is modeling to the end of the variable name, so <code>gender**m**</code> means the effect of being male on the relationship between actual and desired weight compared to the reference group (females).</p>
<p>What about an interaction? Does gender <em>change</em> the relationship between acutal and desired weight? Interaction terms are added using a <code>*</code>.</p>
<pre class="r"><code>summary(lm(wtdesire ~ weight + gender + weight*gender, data=lt250))</code></pre>
<pre><code>## 
## Call:
## lm(formula = wtdesire ~ weight + gender + weight * gender, data = lt250)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -105.088   -6.416   -0.075    6.419  123.249 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    66.393808   0.624130 106.378  &lt; 2e-16 ***
## weight          0.444570   0.004079 108.983  &lt; 2e-16 ***
## genderm        -7.755831   1.074991  -7.215  5.6e-13 ***
## weight:genderm  0.194001   0.006227  31.157  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 12.69 on 19345 degrees of freedom
## Multiple R-squared:  0.8157, Adjusted R-squared:  0.8157 
## F-statistic: 2.855e+04 on 3 and 19345 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The interaction term is significant.</p>
</div>
</div>
<div id="advanced-analyses" class="section level1">
<h1>Advanced Analyses</h1>
<ul>
<li>Non-parametric tests</li>
<li>Generalized Linear Models</li>
<li>Time Series</li>
<li>Factor Analysis &amp; Principle Component Analyses</li>
<li>Cluster Analysis
<ul>
<li>k-nearest neighbors</li>
<li>hierarchical clustering</li>
</ul></li>
<li>Tree-Based Models
<ul>
<li>Decision Trees</li>
<li>Random Forests</li>
</ul></li>
<li>Bootstrapping standard errors</li>
<li>Bayesian analysis using JAGS <a href="https://www.amazon.com/Doing-Bayesian-Data-Analysis-Second/dp/0124058884" class="uri">https://www.amazon.com/Doing-Bayesian-Data-Analysis-Second/dp/0124058884</a></li>
</ul>
</div>

                        </div>
                        
                        
                        <div id="comments">
                            <div id="disqus_thread"></div>
<script type="application/javascript">
    var disqus_config = function () {
    
    
    
    };
    (function() {
        if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
            document.getElementById('disqus_thread').innerHTML = 'Disqus comments not available by default when the website is previewed locally.';
            return;
        }
        var d = document, s = d.createElement('script'); s.async = true;
        s.src = '//' + "devcows" + '.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="https://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
                        </div>
                        

                    </div>
                    

                    

                    

                    <div class="col-md-3">

                        

                        

<div class="panel panel-default sidebar-menu">

    <div class="panel-heading">
      <h3 class="panel-title">Search</h3>
    </div>

    <div class="panel-body">
        <form action="//google.com/search" method="get" accept-charset="UTF-8" role="search">
            <div class="input-group">
                <input type="search" name="q" class="form-control" placeholder="Search">
                <input type="hidden" name="sitesearch" value="/">
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-template-main"><i class="fas fa-search"></i></button>
                </span>
            </div>
        </form>
    </div>
</div>







<div class="panel panel-default sidebar-menu">

    <div class="panel-heading">
        <h3 class="panel-title">Categories</h3>
    </div>

    <div class="panel-body">
        <ul class="nav nav-pills nav-stacked">
            
            
            <li>
                <a href="/categories/analysis">analysis (1)</a>
            </li>
            
            <li>
                <a href="/categories/certificate">certificate (2)</a>
            </li>
            
            <li>
                <a href="/categories/classes">classes (2)</a>
            </li>
            
            <li>
                <a href="/categories/conference">conference (1)</a>
            </li>
            
            <li>
                <a href="/categories/dsi">dsi (3)</a>
            </li>
            
            <li>
                <a href="/categories/event">event (8)</a>
            </li>
            
            <li>
                <a href="/categories/install">install (1)</a>
            </li>
            
            <li>
                <a href="/categories/learning">learning (7)</a>
            </li>
            
            <li>
                <a href="/categories/logistics">logistics (2)</a>
            </li>
            
            <li>
                <a href="/categories/predictive_analytics">predictive_analytics (1)</a>
            </li>
            
            <li>
                <a href="/categories/python">python (2)</a>
            </li>
            
            <li>
                <a href="/categories/seminar">seminar (4)</a>
            </li>
            
            <li>
                <a href="/categories/starting">starting (1)</a>
            </li>
            
            <li>
                <a href="/categories/tableau">tableau (1)</a>
            </li>
            
            <li>
                <a href="/categories/viz">viz (1)</a>
            </li>
            
            <li>
                <a href="/categories/workshop">workshop (12)</a>
            </li>
            
        </ul>
    </div>

</div>








<div class="panel sidebar-menu">

    <div class="panel-heading">
        <h3 class="panel-title">Tags</h3>
    </div>

    <div class="panel-body">
        <ul class="tag-cloud">
            
            
            <li>
                <a href="/tags/analysis"><i class="fas fa-tags"></i> analysis</a>
            </li>
            
            <li>
                <a href="/tags/analytics"><i class="fas fa-tags"></i> analytics</a>
            </li>
            
            <li>
                <a href="/tags/bayes"><i class="fas fa-tags"></i> bayes</a>
            </li>
            
            <li>
                <a href="/tags/bioinformatics"><i class="fas fa-tags"></i> bioinformatics</a>
            </li>
            
            <li>
                <a href="/tags/blogdown"><i class="fas fa-tags"></i> blogdown</a>
            </li>
            
            <li>
                <a href="/tags/career"><i class="fas fa-tags"></i> career</a>
            </li>
            
            <li>
                <a href="/tags/chicostate"><i class="fas fa-tags"></i> chicostate</a>
            </li>
            
            <li>
                <a href="/tags/coding"><i class="fas fa-tags"></i> coding</a>
            </li>
            
            <li>
                <a href="/tags/collaboration"><i class="fas fa-tags"></i> collaboration</a>
            </li>
            
            <li>
                <a href="/tags/community"><i class="fas fa-tags"></i> community</a>
            </li>
            
            <li>
                <a href="/tags/cpp"><i class="fas fa-tags"></i> cpp</a>
            </li>
            
            <li>
                <a href="/tags/curriculum"><i class="fas fa-tags"></i> curriculum</a>
            </li>
            
            <li>
                <a href="/tags/data_management"><i class="fas fa-tags"></i> data_management</a>
            </li>
            
            <li>
                <a href="/tags/datacleaning"><i class="fas fa-tags"></i> datacleaning</a>
            </li>
            
            <li>
                <a href="/tags/dataviz"><i class="fas fa-tags"></i> dataviz</a>
            </li>
            
            <li>
                <a href="/tags/dsi"><i class="fas fa-tags"></i> dsi</a>
            </li>
            
            <li>
                <a href="/tags/event"><i class="fas fa-tags"></i> event</a>
            </li>
            
            <li>
                <a href="/tags/faculty"><i class="fas fa-tags"></i> faculty</a>
            </li>
            
            <li>
                <a href="/tags/fun"><i class="fas fa-tags"></i> fun</a>
            </li>
            
            <li>
                <a href="/tags/hacking"><i class="fas fa-tags"></i> hacking</a>
            </li>
            
            <li>
                <a href="/tags/homebrew"><i class="fas fa-tags"></i> homebrew</a>
            </li>
            
            <li>
                <a href="/tags/internship"><i class="fas fa-tags"></i> internship</a>
            </li>
            
            <li>
                <a href="/tags/job"><i class="fas fa-tags"></i> job</a>
            </li>
            
            <li>
                <a href="/tags/networking"><i class="fas fa-tags"></i> networking</a>
            </li>
            
            <li>
                <a href="/tags/osx"><i class="fas fa-tags"></i> osx</a>
            </li>
            
            <li>
                <a href="/tags/predictive-analytics"><i class="fas fa-tags"></i> predictive-analytics</a>
            </li>
            
            <li>
                <a href="/tags/programming"><i class="fas fa-tags"></i> programming</a>
            </li>
            
            <li>
                <a href="/tags/python"><i class="fas fa-tags"></i> python</a>
            </li>
            
            <li>
                <a href="/tags/r"><i class="fas fa-tags"></i> r</a>
            </li>
            
            <li>
                <a href="/tags/reading"><i class="fas fa-tags"></i> reading</a>
            </li>
            
            <li>
                <a href="/tags/rmarkdown"><i class="fas fa-tags"></i> rmarkdown</a>
            </li>
            
            <li>
                <a href="/tags/rstudio"><i class="fas fa-tags"></i> rstudio</a>
            </li>
            
            <li>
                <a href="/tags/security"><i class="fas fa-tags"></i> security</a>
            </li>
            
            <li>
                <a href="/tags/seminar"><i class="fas fa-tags"></i> seminar</a>
            </li>
            
            <li>
                <a href="/tags/shell"><i class="fas fa-tags"></i> shell</a>
            </li>
            
            <li>
                <a href="/tags/spreadsheets"><i class="fas fa-tags"></i> spreadsheets</a>
            </li>
            
            <li>
                <a href="/tags/sql"><i class="fas fa-tags"></i> sql</a>
            </li>
            
            <li>
                <a href="/tags/stan"><i class="fas fa-tags"></i> stan</a>
            </li>
            
            <li>
                <a href="/tags/statistics"><i class="fas fa-tags"></i> statistics</a>
            </li>
            
            <li>
                <a href="/tags/storms"><i class="fas fa-tags"></i> storms</a>
            </li>
            
            <li>
                <a href="/tags/studentjob"><i class="fas fa-tags"></i> studentjob</a>
            </li>
            
            <li>
                <a href="/tags/studentsuccess"><i class="fas fa-tags"></i> studentsuccess</a>
            </li>
            
            <li>
                <a href="/tags/swcarpentry"><i class="fas fa-tags"></i> swcarpentry</a>
            </li>
            
            <li>
                <a href="/tags/tenuretrack"><i class="fas fa-tags"></i> tenuretrack</a>
            </li>
            
            <li>
                <a href="/tags/theme"><i class="fas fa-tags"></i> theme</a>
            </li>
            
            <li>
                <a href="/tags/tidy"><i class="fas fa-tags"></i> tidy</a>
            </li>
            
            <li>
                <a href="/tags/tutoring"><i class="fas fa-tags"></i> tutoring</a>
            </li>
            
            <li>
                <a href="/tags/variance"><i class="fas fa-tags"></i> variance</a>
            </li>
            
            <li>
                <a href="/tags/volunteer"><i class="fas fa-tags"></i> volunteer</a>
            </li>
            
            <li>
                <a href="/tags/website"><i class="fas fa-tags"></i> website</a>
            </li>
            
            <li>
                <a href="/tags/women"><i class="fas fa-tags"></i> women</a>
            </li>
            
            <li>
                <a href="/tags/workshop"><i class="fas fa-tags"></i> workshop</a>
            </li>
            
            <li>
                <a href="/tags/workshops"><i class="fas fa-tags"></i> workshops</a>
            </li>
            
        </ul>
    </div>

</div>






                        

                    </div>
                    

                    

                </div>
                

            </div>
            
        </div>
        
        <footer id="footer">
    <div class="container">

        
        <div class="col-md-4 col-sm-6">
            <h4>About us</h4>

            <p>The Chico State Data Science Initative strives to foster a 
                      data-empowered society working within a culture of equity-minded
                      open science. We do so by connecting people to opportunities
                      to learn new skills and engage in impactful research across
                      the spectrum of disciplines. 
                     <br>
                  </p>

            <hr class="hidden-md hidden-lg hidden-sm">

        </div>
        
          <div class="col-md-4 col-sm-6">
            <h4>What we do</h4>
            <p>
                <ul>
                  <li>Curriculum Development</li>
                  <li>Professional Data Skills Training</li>
                  <li>Data Wrangling/Analysis</li>
                  <li>Interactive Dashboard Storytelling</li>
                  <li>Student Internships</li>
                  <li>Project/Thesis Consulting</li>
                </ul> 
            </p>
            

            <hr class="hidden-md hidden-lg hidden-sm">

        </div>
        
        
        

        

        
        <div class="col-md-4 col-sm-6">

          <h4>Contact</h4>

            <p class="text-uppercase"><strong>Data Science Initative</strong>
        <br><a href="mailto:datascience@csuchico.edu">datascience@csuchico.edu</a>
      </p>
      

            <a href="https://www.csuchico.edu/datascience/" 
            class="btn btn-small btn-template-main">Learn More about our programs</a>

            <hr class="hidden-md hidden-lg hidden-sm">

        </div>
        
        

    </div>
    
</footer>







<div id="copyright">
    <div class="container">
        <div class="col-md-12">
            
            <p class="pull-left">Copyright (c) 2020, Robin Donatello; all rights reserved.</p>
            
            <p class="pull-right">
              Template by <a href="https://bootstrapious.com/p/universal-business-e-commerce-template">Bootstrapious</a>.
              

              Ported to Hugo by <a href="https://github.com/devcows/hugo-universal-theme">DevCows</a>.
            </p>
        </div>
    </div>
</div>





    </div>
    

    
<script src="//code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/Counter-Up/1.0/jquery.counterup.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-parallax/1.1.3/jquery-parallax.js"></script>

<script src="/js/front.js"></script>


<script src="/js/owl.carousel.min.js"></script>



  </body>
</html>
